spring:
  jpa:
    properties:
      format_sql : true
    database-platform: org.hibernate.dialect.MySQL5Dialect



#DataSource 1
app:
  datasource:
    client1:
      driverClassName: com.mysql.cj.jdbc.Driver
      jdbcUrl: jdbc:mysql://115.68.228.63:3306/multi01?serverTimezone=UTC&characterEncoding=UTF-8
      username: root
      password: tck1966!
    client2:
      driverClassName: com.mysql.cj.jdbc.Driver
      jdbcUrl: jdbc:mysql://115.68.228.63:3306/multi02?serverTimezone=UTC&characterEncoding=UTF-8
      username: root
      password: tck1966!